// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNQWLiERsO_fqn69PmKkraD6YYHXa0Kmk',
    appId: '1:155085357502:web:7b8ae3cea82cec369cb9ef',
    messagingSenderId: '155085357502',
    projectId: 'random-travel-27cc6',
    authDomain: 'random-travel-27cc6.firebaseapp.com',
    storageBucket: 'random-travel-27cc6.appspot.com',
    measurementId: 'G-FY7RPESRCV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3905vsDp6B5Wt3x0xHg2MgEi-SEnEgBM',
    appId: '1:155085357502:android:c80a53073352e6f19cb9ef',
    messagingSenderId: '155085357502',
    projectId: 'random-travel-27cc6',
    storageBucket: 'random-travel-27cc6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB01ATI6ck8j0_1RLUY4uoDwSS2-rrWwIg',
    appId: '1:155085357502:ios:b0f37cc98de87f3a9cb9ef',
    messagingSenderId: '155085357502',
    projectId: 'random-travel-27cc6',
    storageBucket: 'random-travel-27cc6.appspot.com',
    iosBundleId: 'com.example.thailandRandomTravel',
  );
}